version: '3'

services:
    app:
        build: .
        environment:
            NODE_ENV: development
            MONGO_URI: 'mongodb://db:27017/example'
            PORT: 3000
            BLING_URL: https://bling.com.br/Api/v2/pedido/json/
            BLING_API_KEY: 
        depends_on:
            - db
        ports:
            - '3000:3000'
        command: 'node dist/server.js'

    worker:
        build: 
            context: .
            dockerfile: Dockerfile-worker
        depends_on: 
            - db
        environment:
            NODE_ENV: development
            MONGO_URI: 'mongodb://db:27017/example'
            BLING_URL: https://bling.com.br/Api/v2/pedido/json/
            PIPEDRIVE_URL: https://api.pipedrive.com/v1/
            BLING_API_KEY: 
            PIPEDRIVE_API_KEY: 
        command: 'node dist/crons/createOrders.js'

    db:
        image: mongo
        container_name: mongo
        ports:
        - '27017:27017'